apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 12.6.4
    helm:
      parameters:
      - name: service.type
        value: NodePort
      - name: service.nodePorts.api
        value: "30900"
      - name: service.nodePorts.console
        value: "30901"
      - name: auth.rootUser
        value: minioadmin
      - name: auth.rootPassword
        value: minioadmin123
      - name: persistence.enabled
        value: "true"
      - name: persistence.size
        value: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
