apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.5
    helm:
      parameters:
      - name: service.type
        value: NodePort
      - name: service.apiPort
        value: "30900"
      - name: service.consolePort
        value: "30901"
      - name: rootUser
        value: minioadmin
      - name: rootPassword
        value: minioadmin123
      - name: persistence.enabled
        value: "true"
      - name: persistence.size
        value: 50Gi
      - name: mode
        value: standalone
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
